name: daily-login-assistant

services:
  daily-login-assistant:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_FRONTEND: noninteractive
        TZ: Japan
        DOCKER_IMAGE_NAME_TEMPLATE: "mcr.microsoft.com/playwright:v1.55.0-noble"
    container_name: daily-login-assistant
    volumes:
      - profiles_data:/app/profiles
      - logs_data:/app/logs
      - screenshots_data:/app/screenshots
    environment:
      NODE_ENV: production
      WORKER_ID: ${HOSTNAME:-worker-1}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
      TZ: Japan
    ports:
      - '127.0.0.1:8001:3001'
    working_dir: /app
    restart: unless-stopped
    user: "1001"
    init: false
    ipc: host
networks:
  default:
    driver: bridge

volumes:
  profiles_data:
  logs_data:
  screenshots_data:
