#!/bin/bash
SESSION_TOKEN={{SESSION_TOKEN}}
REMOTE_SSH_HOST={{REMOTE_SSH_HOST}}
REMOTE_SSH_PORT={{REMOTE_SSH_PORT}}
REMOTE_SSH_USER={{REMOTE_SSH_USER}}
SSH_PASSWORD={{SSH_PASSWORD}}
API_ENDPOINT={{API_ENDPOINT}}
ALLOWED_ORIGIN={{ALLOWED_ORIGIN}}
