services:
  # Ubuntu with systemd (working approach)
  ubuntu-systemd:
    image: ubuntu:24.04
    container_name: ubuntu-systemd-test
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      # Mount the script for testing
      - ../docker/dailycheckin.sh:/tmp/dailycheckin.sh:ro
      # Mount cgroup for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - container=docker
    command: >
      bash -c "
        # Install systemd first
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y systemd systemd-sysv dbus iproute2 curl wget
        rm -rf /var/lib/apt/lists/*
        # Remove unnecessary services to avoid conflicts
        systemctl mask dev-hugepages.dev-hugepages.service dev-mqueue.dev-mqueue.service sys-kernel-config.mount sys-kernel-debug.mount sys-fs-fuse-connections.mount || true
        echo 'Systemd installed and ready. Ready for manual testing.'
        echo 'Run: bash /tmp/dailycheckin.sh'
        # Keep container running
        tail -f /dev/null
      "

