# Remote Docker Deployment Settings
# Optimized for headless server with cookie-based authentication

settings:
  global:
    defaultTimeout: 30000
    maxConcurrentTasks: 5  # Increased for multiple profiles
    logLevel: "info"
    retryFailedTasksAfter: 3600000  # 1 hour

  notifications:
    sendOnSuccess: true  # Get notified on successful check-ins
    sendOnFailure: true  # Get notified on failures
    sendDailySummary: true  # Daily summary report
    summaryTime: "20:00"  # 8 PM summary
    timezone: "Asia/Hong_Kong"  # Your timezone

    # Session expiration alerts
    sessionExpirationWarning: true  # Alert when cookies might expire
    sessionExpirationDays: 7  # Warn 7 days before expiration

  browser:
    headless: true  # CRITICAL for Docker
    userDataDir: "./profiles"
    slowMo: 50  # Small delay between actions for stability
    args:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--disable-web-security"
      - "--disable-features=VizDisplayCompositor"
      - "--disable-blink-features=AutomationControlled"  # Anti-detection

  scheduler:
    enabled: true
    checkInterval: 60000  # Check every minute
    maxMissedSchedules: 3

  webApi:
    enabled: true
    port: 3001
    host: "0.0.0.0"  # CRITICAL: Listen on all interfaces for Docker
    corsEnabled: true  # Allow browser access from any origin

  reliability:
    circuitBreaker:
      enabled: true
      failureThreshold: 5  # Open circuit after 5 failures
      resetTimeout: 300000  # Try again after 5 minutes

  storage:
    profilesDir: "./profiles/user-guided"
    logsDir: "./logs"
    screenshotsDir: "./screenshots"
    maxLogSizeMB: 100
    maxScreenshotAgeDays: 7  # Auto-cleanup old screenshots
