websites:
  - id: example1
    name: "Example Website 1"
    url: "https://example1.com/login"
    enabled: true
    schedule:
      time: "23:07"
      timezone: "America/New_York"
    credentials:
      username_env: "EXAMPLE1_USERNAME"
      password_env: "EXAMPLE1_PASSWORD"
    selectors:
      username: ["#username", "[name='email']", ".login-username"]
      password: ["#password", "[name='password']", ".login-password"]
      loginButton: ["#login", ".login-btn", "[type='submit']"]
      checkinButton: [".checkin", "#daily-checkin", ".attendance"]
      logoutIndicator: [".logout", ".profile-menu", ".user-dropdown"]
    automation:
      waitForNetworkIdle: true
      typingDelay: 100
      navigationTimeout: 30000
      retryAttempts: 3
      retryDelay: 5000
    security:
      useStealth: true
      antiDetection: true
      randomDelays: true

  - id: example2
    name: "Example Website 2"
    url: "https://example2.com/signin"
    enabled: false
    schedule:
      time: "10:30"
      timezone: "America/New_York"
    credentials:
      username_env: "EXAMPLE2_USERNAME"
      password_env: "EXAMPLE2_PASSWORD"
    selectors:
      username: ["#email", "[name='username']"]
      password: ["#pwd", "[name='password']"]
      loginButton: [".btn-login", "#signin"]
      checkinButton: [".daily-check", ".check-in"]
      logoutIndicator: [".user-menu", ".logout-link"]
    automation:
      waitForNetworkIdle: true
      typingDelay: 150
      navigationTimeout: 45000
      retryAttempts: 2
      retryDelay: 3000
    security:
      useStealth: true
      antiDetection: true
      randomDelays: true